### ISSUE TITLE
Why October or RedCross is recomended?

### ISSUE THREAD

**Issue by John3** [ajdumanhug/oscp-practice#1]
I see in the first set "October" but that VM include ASLR.

And the RedCross you need to use PAM.

Pretty sure those topic are not included in the syllabus.

How was you criteria to took those VM as reference?

**Comment by ajdumanhug** [comment]
Here: https://docs.google.com/spreadsheets/d/1dwSMIAPIam0PuRBkCiDI88pU3yzrqqHkDtBngUHNCw8/edit#gid=1839402159

**Comment by John3** [comment]
I know that list, it seems the doc was updated recently and added that VM. Either way ASLR is for OSCE 😄 

If you have a chance take a look and replace it.
